### ISSUE TITLE
Adding Header to CustomCollectionView

### ISSUE THREAD

**Issue by Mamonaku** [brightec/CustomCollectionViewLayout#10]
Hello, and thanks for this great code!

I'm trying to add a header to the view, using the following:
- in the controller, register the Header view supplementary view
```
collectionView .registerNib(UINib(nibName: "HeaderMulticolumn", bundle: nil), forSupplementaryViewOfKind: UICollectionElementKindSectionHeader, withReuseIdentifier: "Header")
```

then later, implement the delegate methods:

```
func collectionView(collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, atIndexPath indexPath: NSIndexPath) -> UICollectionReusableView {

let headerView = collectionView.dequeueReusableSupplementaryViewOfKind(kind, withReuseIdentifier: "Header", forIndexPath: indexPath) 
            
            headerView.backgroundColor = UIColor.blueColor();
            return headerView
}
```

and in the layout class
```

    override func layoutAttributesForSupplementaryViewOfKind(elementKind: String, atIndexPath indexPath: NSIndexPath) -> UICollectionViewLayoutAttributes? {
        let attributes = UICollectionViewLayoutAttributes(forSupplementaryViewOfKind: UICollectionElementKindSectionHeader, withIndexPath: indexPath)
        
        let headerHeight = CGFloat(50)
        attributes.frame = CGRectMake(0, 0, self.collectionView!.frame.size.width, headerHeight)
        
        return attributes;
    }

```

It's not necessarily a question about your code, but I can't get collectionView: viewForSupplementaryElementOfKind: to be called at all. Is there any chance you could point at the right direction to have Headers added to your custom UICollectionView class?
note: I tried with different layout classes, without changing the controller class, and managed to have headers added, so it must come from the way CustomCollectionViewLayout operates (but I can't see why)
thanks!

**Comment by Mamonaku** [comment]
ok, found it.

**Comment by juliusbtesh** [comment]
I know this has been quite a while since this question was asked. But I am currently trying to get a custom footer view with this layout and can't get it working. Can you let me know how you were able to get the header?

Thanks! (Hopefully this gets seen)

**Comment by ismaiI1** [comment]
@Mamonaku How did you add header row? can you tell please :)
